<div>
	<section class="intro">
		<div class="content">
			<div class="copy">
				<h1>Cascade Climate Privacy Policy</h1>
				<p class="date">Last updated: May 13, 2025</p>
				<hr>
			</div>
		</div>
	</section>

	<main>
		<h2 style="text-align: justify;">1. Overview.</h2>
		<p style="text-align: justify;">This privacy policy (the &ldquo;Policy&rdquo;) is designed to inform users of our website (<a href="https://cascadeclimate.org/" target="_blank" rel="noopener"><span style="color: #0000ff;">https://cascadeclimate.org/</span></a>) about how Cascade Climate collects, uses, and/or shares personal information in connection with the use of our website.&nbsp; Cascade Climate takes individual privacy seriously and we endeavor to inform you of the uses that we have for the information described in this policy, which we obtain from you (collectively, &ldquo;Personal Information&rdquo;).&nbsp; We will take reasonable commercial steps to protect your privacy consistent with the guidelines set forth in this Policy and with applicable federal and state laws.&nbsp;&nbsp;</p>
		<p style="text-align: justify;">In this Policy, &ldquo;Provider,&rdquo; "user," &ldquo;your,&rdquo; or "you" refers to any individual from whom we obtain Personal Information, whether by using our website, submitting any request through our website, creating any account with our website, or participating in any other activities or engaging with us.&nbsp; As the manners in which we obtain Personal Information and our uses for Personal Information may change, we encourage you to return to and reread this Policy from time to time.&nbsp;&nbsp;</p>
		<p style="text-align: justify;">By accessing or using our website, you acknowledge that you have read, understand, and agree to be bound by this Policy, and consent to the transfer, use, and disclosure of your Personal Information as described in this Policy.&nbsp; If you do not agree to the terms of this Policy, do not use our website.</p>
		<h2 style="text-align: justify;">2. What Information Do We Collect?&nbsp;&nbsp;</h2>
		<p style="text-align: justify;">We collect two types of Personal Information from you: (i) Individualized Information, and (ii) Device Information:</p>
		<h3 style="text-align: justify;">Individualized Information.</h3>
		<p style="text-align: justify;">We may collect certain Personal Information from you when you use our website.&nbsp; Such Personal Information may include:&nbsp;</p>
		<ul>
		<li>Your first and last name&nbsp;</li>
		<li>Email address</li>
		<li>Institution</li>
		<li>Position</li>
		<li>Telephone number</li>
		<li>Postal address</li>
		</ul>
		<h3 style="text-align: justify;">Device Information.</h3>
		<p style="text-align: justify;">We may collect certain web tracking information about the device that you use to connect to and use our website.&nbsp; Depending on the circumstances, this &ldquo;Device Information&rdquo; may include, but is not limited to:&nbsp;</p>
		<ul>
		<li>Information about your web browser (e.g., browser type, domain names, access times, and operating system)</li>
		<li>Internet protocol address (&ldquo;IP address&ldquo;)</li>
		<li>Web pages that you have viewed and your time spent on each one</li>
		<li>Web pages or search terms that referred you to our website</li>
		<li>How you interact with our website&nbsp;</li>
		<li>Your user preferences, time zone, or information about the cookies installed on your device.&nbsp;&nbsp;</li>
		</ul>
		<p style="text-align: justify;">As described in Section 3, we may use cookies and navigational data like Uniform Resource Locators (&ldquo;URLs&rdquo;) to gather information regarding the date and time of your visit and the information for which you searched and viewed.</p>
		<h2 style="text-align: justify;">3. Cookies.&nbsp;&nbsp;</h2>
		<h3 style="text-align: justify;">In General.</h3>
		<p style="text-align: justify;"><span style="color: #262626;">A cookie is a small file containing a string of characters that is sent to your device or browser when you use a website or mobile application.&nbsp; When you use the website or mobile application again, the cookie allows it to recognize your device or browser.&nbsp; Cookies also offer a form of convenience in that they may store preferences and other information and, in doing so, save you time by allowing a website or mobile application to identify preferences that you have displayed or selected in the past.&nbsp; Our website may use cookies for purposes including, but not limited to, maintaining and improving our website&rsquo;s functionality, making our website more efficient to you, generally customizing our website to improve your experience, and offering advertisements through our website that are relevant to you.</span></p>
		<h4 style="text-align: justify;">How Can You Control Cookies?</h4>
		<p style="text-align: justify;"><span style="color: #262626;">You have the right to decide whether to accept, block, or reject cookies.&nbsp; You can generally select to accept, block, or reject cookies through your own device or browser controls.&nbsp; You should visit your device settings or browser&rsquo;s help menu for instructions on how to make this selection and additional device-specific and browser-specific information about cookies.&nbsp; </span>Cascade Climate<span style="color: #262626;"> is not responsible for making this selection for you.&nbsp; If you choose to reject cookies, you may still use </span>our website<span style="color: #262626;">, but your access to some functionality and areas of </span>our website <span style="color: #262626;">may be restricted.&nbsp; For more information on how cookies work and how to control them, you may visit </span><a href="http://www.allaboutcookies.org" target="_blank" rel="noopener"><span style="color: #0000ff;">www.allaboutcookies.org</span></a><span style="color: #262626;">.&nbsp;&nbsp;</span></p>
		<h2 style="text-align: justify;">4. How Do We Use Your Information?</h2>
		<h3 style="text-align: justify;">Use of Personal Information.</h3>
		<p style="text-align: justify;">We may use Personal Information for a variety of purposes including, but not limited to: providing or communicating with you regarding our products and services; establishing and maintaining User accounts; User data submission; providing customer service; processing orders and transactions (including payments); shipping products or information to you; verifying user information; detecting security incidents that may compromise the confidentiality of Personal Information in our possession; maintaining or improving the quality or safety of our products or services; processing job applications; or enforcing our legal rights or as required by applicable law or requested by any judicial process or government agency.</p>
		<h3 style="text-align: justify;">Use of Device Information.</h3>
		<p style="text-align: justify;">We may use Device Information for a variety of purposes including, but not limited to: helping us screen for and prevent potential risk and fraud (in particular, through any IP address we collect from you); diagnosing and mitigating errors on our website; administering and optimizing our website; making our products and services more useful to you; generating analytics about how our customers browse and interact with our website; assessing the success of any marketing or advertising campaigns; or storing user preferences.&nbsp; Using Device Information for these purposes allows us to determine which features on our website users like best and generally helps us improve our website and personalize each user&rsquo;s experience.</p>
		<h3 style="text-align: justify;">Minimum Amount Necessary.&nbsp;&nbsp;</h3>
		<p style="text-align: justify;">Cascade Climate will not use your Personal Information beyond the minimum amount and scope necessary to achieve the above purposes without first obtaining your consent, unless otherwise permitted or required by applicable law.</p>
		<h3 style="text-align: justify;">License to Use Your Content.&nbsp;&nbsp;</h3>
		<p style="text-align: justify;">Please note that by sending us messages or inquiries, uploading files, inputting data, or engaging in any other form of communication through the our website, you are granting us a license to use, reproduce, disclose, publish, distribute, and otherwise exploit in any manner the content of any such message, inquiry, file, data, or communication.&nbsp; This license is granted to us without restriction and without the requirement that we compensate you in any way.&nbsp; We are under no obligation to maintain any such message, inquiry, file, data, or communication in confidence, or to provide you with any response or confirmation of receipt.</p>
		<h3 style="text-align: justify;">Aggregated Data.</h3>
		<p style="text-align: justify;">To the extent permitted under applicable law, we may also create statistical, de-identified, anonymized, or aggregated data (collectively, &ldquo;Aggregated Data&rdquo;) relating to our users and our website to use for analytical, research, or any other legal purposes.&nbsp; Aggregated Data includes data derived from Personal Information and data collected by Cascade Climate from other sources that has been anonymized so that it does not relate to and could not reasonably be used to identify any individual.</p>
		<h3 style="text-align: justify;">Email Communications.</h3>
		<p style="text-align: justify;">If you provide us with your email address, we may in the future begin to send you promotional emails, including newsletters.&nbsp; If you wish to opt out of these communications, you may do so by following the "unsubscribe" instructions in the email.</p>
		<h2 style="text-align: justify;">5. What Information Do We Share or Disclose?</h2>
		<h3 style="text-align: justify;">Disclosure of Personal Information.</h3>
		<p style="text-align: justify;">We generally will not share or disclose Personal Information with any third-parties, except under the following circumstances:</p>
		<ol>
		<li>When you have consented to us sharing or disclosing your Personal Information.</li>
		<li>When Personal Information is shared with or disclosed to a parent company, subsidiary, joint venture, or other entity under common control with us in order to achieve any of the purposes described in Section 4.</li>
		<li>Subject to the terms of a confidentiality agreement, in connection with, and for the purposes of, a business deal (or negotiation of a business deal) involving the sale or transfer of all or a part of our business or assets.&nbsp; These deals may include any merger, financing, acquisition, or bankruptcy proceeding.</li>
		<li>With a third-party contractor engaged to provide management, administrative, shipping and fulfillment, or support services on our behalf (a "Contractor"), which require the Contractor to have access to Personal Information.&nbsp; In this instance, we enter into an agreement with the Contractor limiting the Contractor&rsquo;s use of the Personal Information to the minimum amount necessary to perform our website; requiring the Contractor to report any suspected or actual breach of security or other incident related to the Personal Information to us; and requiring the Contractor to adhere to the same level of privacy requirements that are required of us by all applicable law.&nbsp; By accessing or using our website, you consent to our sharing your Personal Information with any Contractors and to the Contractors&rsquo; use of your Personal Information in accordance with all applicable law, this Policy, and the other terms and conditions applicable to our website.</li>
		<li>To detect, prevent, or otherwise address security, fraud, or technical issues.</li>
		<li>To ensure the personal safety of any individual, including our employees or job applicants, users of our website, or members of the general public.</li>
		<li>To the extent required to comply with legal obligations, processes, or requests; enforce our contracts and agreements (including this Policy); or protect or defend our legal rights.</li>
		</ol>
		<h3 style="text-align: justify;">Aggregated Data.</h3>
		<p style="text-align: justify;">To the extent permitted by applicable law, we may in our sole discretion disclose any Aggregated Data that does not contain Personal Information to any third-parties for any legal purpose.</p>
		<h3 style="text-align: justify;">Network Operators.</h3>
		<p style="text-align: justify;">Use of our website may involve the use of third-party search engine operators or telecommunications carriers.&nbsp; These operators are not our Contractors, and any information that these operators collect in connection with your use of our website is not a part of our collected Personal Information and is not subject to this Policy.&nbsp; We are not responsible for the acts or omissions of these operators.</p>
		<h2 style="text-align: justify;">6. Your Rights Regarding Your Information.</h2>
		<h3 style="text-align: justify;">Removals.&nbsp;&nbsp;</h3>
		<p style="text-align: justify;">If you would like your Personal Information to be permanently removed from our database, please contact us by email at <a href="mailto:hello@cascadeclimate.org" target="_blank" rel="noopener">hello@cascadeclimate.org</a> or call ‪(508) 203-1425‬. We may ask you to provide a copy of your driver&rsquo;s license or other identifying documents to assist us in processing your request.&nbsp; Cascade Climate may still contact users who have requested that their Personal Information be permanently removed for administrative purposes.&nbsp; The removal of your Personal Information may take some time to complete, consistent with applicable law.&nbsp; Please also note that the removal of any Personal Information will not necessarily result in the removal of records of past transactions or the deletion of information stored in our data archives.&nbsp; To the extent permitted by applicable law, we may in our reasonable discretion respond to a request to remove by converting the Personal Information into Aggregated Data, which is not subject to further requests for removal.&nbsp;</p>
		<h3 style="text-align: justify;">Access and Corrections.&nbsp;</h3>
		<p style="text-align: justify;">Cascade Climate will, to the best of our ability and in accordance with applicable law, allow you to access and review the categories and specific pieces of Personal Information we have collected from you, the sources from which we have collected such Personal Information, the purposes for which we have used such Personal Information, and the types of third-parties to which we have disclosed such Personal Information for a purpose described under this Policy.&nbsp; We will also allow you to correct or add to your Personal Information held in our database.&nbsp; To make any such request, please contact us by email at <a href="mailto:hello@cascadeclimate.org" target="_blank" rel="noopener">hello@cascadeclimate.org</a> or call&nbsp; ‪(508) 203-1425‬. We may ask you to provide a copy of your driver&rsquo;s license or other identifying documents to assist us in processing your request.&nbsp;&nbsp;</p>
		<h3 style="text-align: justify;">Timeframe.&nbsp;&nbsp;</h3>
		<p style="text-align: justify;">Cascade Climate will, to the best of our ability and in accordance with applicable law, confirm receipt of any request submitted under this Section 6 within ten (10) days of receipt of the request and respond to the request within forty-five (45) days.&nbsp; If a response requires additional time, we will notify you of the basis for the delay and may extend the timeframe for providing the response up to an additional forty-five (45) days.</p>
		<h3 style="text-align: justify;">Excessive Requests.</h3>
		<p style="text-align: justify;">To the extent permitted by applicable law, if we reasonably determine that a request submitted under this Section 6 is manifestly unfounded or excessive, we may charge a reasonable fee for processing the request or may refuse to process the request.</p>
		<h2 style="text-align: justify;">7. Additional Policies.</h2>
		<h3 style="text-align: justify;">Security.</h3>
		<p style="text-align: justify;">To the extent required by applicable law, Cascade Climate will utilize appropriate, commercially reasonable administrative, physical, and technical safeguards to protect Personal Information.&nbsp; The appropriate safeguards employed by us may vary depending on the nature of Personal Information collected, with more stringent measures applied to information of a sensitive nature.&nbsp; No Internet or software transmission is completely secure, and we cannot guarantee that security breaches will not occur.&nbsp; We are not responsible for the actions of hackers and other unauthorized third-parties that breach our reasonable safeguards.&nbsp; Additionally, you should be aware that certain Personal Information that you provide in connection with your use of our website may remain stored on the device that you use to access our website.&nbsp; You are solely responsible for maintaining the security of your device against unauthorized access.&nbsp; This Policy is not intended to confer, nor does it confer, any rights or remedies to users.</p>
		<h3 style="text-align: justify;">Third-Party Activity.&nbsp;&nbsp;</h3>
		<p style="text-align: justify;">Our website may contain links to other websites, cookies, or other materials from, or which may be operated by, third-party entities.&nbsp; The information practices and privacy policies of these third-party entities may be different than those of Cascade Climate.&nbsp; We are not responsible for any actions or omissions by any such third-party entities.&nbsp; This Policy applies only to Personal Information collected by Cascade Climate.</p>
		<h3 style="text-align: justify;">Data Retention.&nbsp;&nbsp;</h3>
		<p style="text-align: justify;">Unless you ask us to delete your Personal Information sooner, we will maintain it until such time that we determine, in our sole discretion, that (1) it is no longer necessary for any purpose for which Cascade Climate may use it in accordance with this Policy; and (2) it may be destroyed or deleted in accordance with applicable law.</p>
		<h3 style="text-align: justify;">Do Not Track.&nbsp;&nbsp;</h3>
		<p style="text-align: justify;">&ldquo;Do Not Track&rdquo; (DNT) is a web browser setting that informs a website, mobile application, or other service that you do not wish to be tracked.&nbsp; Our website do not respond to Do Not Track (DNT) signals or requests.</p>
		<h3 style="text-align: justify;">Amendments.&nbsp;&nbsp;</h3>
		<p style="text-align: justify;">Cascade Climate will review this Policy from time to time and may modify or amend it as necessary to comply with applicable law.&nbsp; We may also update the Policy to reflect changes to our practices or for other operational reasons.&nbsp; If we make any material changes to how Personal Information is collected, used, disclosed, or transferred, we will notify you of these changes by modifying the version of this Policy that is available for your review on our website.&nbsp; Accordingly, we encourage you to review this Policy from time to time.&nbsp; Notwithstanding any modifications we may make, all Personal Information will be treated in accordance with the version of the Policy that is/was in effect at the time the Personal Information was collected, unless we obtain your consent otherwise.&nbsp;&nbsp;</p>
		<h3 style="text-align: justify;">Accessibility.&nbsp;&nbsp;</h3>
		<p style="text-align: justify;">Any person with a disability that prevents or restricts them from accessing this Policy through Cascade Climate&rsquo;s website may request a copy in an alternative format by contacting us by email at <a href="mailto:hello@cascadeclimate.org" target="_blank" rel="noopener">hello@cascadeclimate.org</a> or calling (508) 203-1425‬.&nbsp;</p>
		<h3 style="text-align: justify;">Children.&nbsp;&nbsp;</h3>
		<p style="text-align: justify;">The Children&rsquo;s Online Privacy Protection Act imposes certain requirements on website operators that have actual knowledge that they collect Personal Information from children.&nbsp; Cascade Climate does not knowingly collect or maintain Personal Information from persons under 18 years of age, and no part of our website is directed at persons under 18.&nbsp; If you are under 18 years of age, please do not use our website.&nbsp; If Cascade Climate learns that Personal Information of persons under the age of 13 has been collected without verifiable parental consent, Cascade Climate will delete the Personal Information.</p>
		<h3 style="text-align: justify;">Users from Outside the United States.&nbsp;&nbsp;</h3>
		<p style="text-align: justify;">Cascade Climate and its servers are located and operate in the United States, subject to the applicable state and federal laws of the United States.&nbsp; Those who choose to access our website do so on their own initiative and at their own risk, and are responsible for complying with all local laws, rules, and regulations.&nbsp; We may limit our website&rsquo; availability, in whole or in part, to any person, geographic area or jurisdiction we choose, at any time and in our sole discretion.&nbsp; We do not represent or warrant that our website, or any part thereof, is appropriate or available for use in any other jurisdiction.&nbsp; If you choose to access or use our website, you consent to the use and disclosure of information in accordance with this Policy and subject to all applicable laws.</p>
		<h3 style="text-align: justify;">Contact.&nbsp;&nbsp;</h3>
		<p style="text-align: justify;">In the event you have any questions for us, wish to submit a complaint about how we have processed any Personal Information, or would like to contact us for any other reasons, please email <a href="mailto:hello@cascadeclimate.org" target="_blank" rel="noopener">hello@cascadeclimate.org</a> or call (508) 203-1425‬. We will deal with any complaints or requests as soon as possible, and without prejudice to you.&nbsp; In the event that you submit a complaint to us, you may of course also file any complaint with a relevant government agency in the state or jurisdiction in which you live or work.</p>
		<h2 style="text-align: justify;">8. Notice for Residents of European Economic Area, United Kingdom, or Switzerland.</h2>
		<h3 style="text-align: justify;">Rights Honored.&nbsp;&nbsp;</h3>
		<p style="text-align: justify;">We will generally make commercially reasonable efforts to honor your data privacy rights upon request, subject to certain limitations.&nbsp; If you reside in the European Economic Area (&ldquo;EEA&rdquo;), UK, or Switzerland, you have the rights, as applicable under the GDPR, to:</p>
		<ol>
		<li>Request an accounting of Personal Information that we possess that pertains to you in an electronically portable format.&nbsp;&nbsp;</li>
		<li>Request that we correct or update Personal Information that pertains to you.</li>
		<li>Request that we delete Personal Information that pertains to you.&nbsp;</li>
		<li>Fully or partially withdraw your consent to the collection, processing, and/or transfer of your Personal Information.</li>
		</ol>
		<h3 style="text-align: justify;">Requests and Complaints.&nbsp;&nbsp;</h3>
		<p style="text-align: justify;">Please contact us by email at <a href="mailto:hello@cascadeclimate.org" target="_blank" rel="noopener">hello@cascadeclimate.org</a> or call (508) 203-1425‬ to request (i) an accounting of your Personal Information; (ii) a correction or update to your Personal Information; (iii) the deletion of your Personal Information; or (iv) to withdraw your consent to the collection, processing, and/or transfer of your Personal Information.&nbsp; If we receive a deletion or withdrawal request, we will no longer process your Personal Information for the above purposes unless there are legitimate grounds for the processing that override your interests, rights, and freedoms, or unless we do so for the establishment, exercise, or defense of legal claims.&nbsp; If you believe we are unlawfully possessing your Personal Information, you have the right to complain to your local data protection supervisory authority.&nbsp; You can find contact details here: <a href="https://edpb.europa.eu/about-edpb/board/members_en" target="_blank" rel="noopener"><span style="color: #0000ff;">https://edpb.europa.eu/about-edpb/board/members_en</span></a>.</p>
		<p style="text-align: justify;">If you reside in the EEA, UK, or Switzerland, please be aware that if you voluntarily provide us with any Personal Information, that information will be transferred from your location to data centers located in the United States for processing, and this transfer will be deemed to have been made with your consent.</p>
		<h2 style="text-align: center;">Effective Date:&nbsp; May 13, 2025</h2>
	</main>
</div>