<script>
	import PDFLink from '$lib/components/PDFLink.svelte';
	import ScrollNav from '$lib/components/ScrollNav.svelte';
    import grants from '$lib/images/nature/grants.webp';
    import landfill from '$lib/images/blog/landfill-gas-projects.webp';
    import redd from '$lib/images/blog/redd.webp';
    import bridge from '$lib/images/nature/bridge.webp';
    
</script>

<div>
	<section class="intro">
		<div class="content">
			<div class="copy">
				<h1>Crossing the Bridge: How Voluntary Climate Finance Can Accelerate Sustained Policy and Industry Adoption</h1>
				<a href="/people/brad-rochlin" style="color: white;">Brad Rochlin</a>,
                <a href="/people/rachel-smith" style="color: white;">Rachel Smith</a>,
                <a href="/people/hara-wang" style="color: white;">Hara Wang</a>
                <p class="date" style="font-weight: 200;">Sep 16, 2025</p>

                <hr>
                
                <p>Cascade <a href="https://cascadeclimate.org/our-work#superpollutantmitigation">recently announced</a> the expansion of our work into the world of super pollutant mitigation to address the urgent risks associated with near-term warming. In the piece, we outline a theory of change in which catalytic voluntary climate finance kickstarts action that helps bridge to a policy-driven end state, where super pollutant reductions are embedded in industry value chains and national climate policies.
                </p><br>

                <p>This policy-driven end state—the “far side” of the bridge—is the ultimate goal. Early projects funded through voluntary climate finance can help make that end state possible by addressing gaps faced when scaling climate solutions and pulling forward engagement by policymakers and industrial actors.
                </p>
			</div>
            <img src={bridge} alt="Enhanced Rock Weathering" />
		</div>

	</section>
	<ScrollNav />
	<main>
    
    <section id="vcf-bridge">
        <h1>Voluntary Climate Financing as a Bridge</h1>

        <p>Most climate solutions address environmental externalities&mdash;costs and benefits that our economic systems don&rsquo;t naturally capture&mdash;that regulation and public policy eventually need to address. &ldquo;End state&rdquo; solutions to internalizing these externalities might look like adoption within compliance markets, sustained development finance, regulation, or integration into industry value chains. However, the path to getting there is rarely obvious, with specific challenges faced along the way.</p>
<p>Today, voluntary climate finance is one of the few tools we can deploy at speed to test and de-risk climate technologies, while closing three critical gaps to scale-up:</p>
<ul>
<li><strong>The </strong><span style="color: #b10202;"><strong>knowledge gap</strong></span><strong>&mdash;building the evidence base for novel climate approaches</strong>. Solutions can&rsquo;t be deployed broadly until we have confidence in their scientific foundations and efficacy in an applied context.&nbsp;</li>
<li><strong>The </strong><span style="color: #0502b1;"><strong>cost gap</strong></span><strong>&mdash;moving climate technologies down the cost curve.</strong> Prohibitive costs stall industry adoption and make government action infeasible.&nbsp;</li>
<li><strong>The </strong><span style="color: #ff7f0e;"><strong>deployment readiness gap</strong></span><strong>&mdash;addressing barriers to real-world implementation for climate technologies prior to scale up.</strong> Government and industry actors can&rsquo;t make large-scale investments if material project execution risks exist.&nbsp;</li>
</ul>
<p>In addition to closing these gaps, early voluntarily-funded projects provide opportunities to engage, incentivize, and build awareness and momentum among key &ldquo;far side&rdquo; policymakers and industrial actors. This early involvement enables &ldquo;far side&rdquo; actors to begin laying bricks for the &ldquo;middle&rdquo; of the bridge&mdash;where they can test emerging technologies, often through R&amp;D and innovation funding.This kickstarts the longer process of policy and industry adoption, exposing decision makers to opportunities earlier in the process and getting them invested in the transition towards the end state.</p>
<p>Voluntary climate finance is not without flaws or debate around its appropriate usage, yet it has repeatedly unlocked momentum that policy and industry later sustained. In what follows, we unpack the gaps outlined above, and highlight case studies illustrating how, despite their imperfections, voluntary projects have catalyzed action and accelerated progress toward the far side of the bridge.</p>

    </section>

	<section id="the-knowledge-gap">
        <h1>1. The Knowledge Gap</h1>
        <h2>Accelerating scientific and technical understanding for novel climate approaches.</h2>
    
        <p>For relatively novel climate approaches with a limited evidence base or outstanding scientific questions, voluntary climate finance can help to close the <span style="color: #b10202;"><strong>knowledge gap</strong></span>. Catalytic voluntary projects test, and ideally validate, a pathways&rsquo; scientific foundations in an applied and limited scale context prior to scale-up or widespread industry adoption.&nbsp;</p>
<p>As an instructive example, the agriculture sector has seen this approach taken in recent years:</p>
<h3>Regenerative agriculture</h3>
<ul>
<li>Regenerative agriculture represents a range of farming practices&mdash;no or reduced tillage, cover crops, rotational grazing, and more&mdash;that restore degraded soils and increase soil organic carbon. Though <a href="https://sustainablefoodtrust.org/news-views/the-many-meanings-of-regenerative-agriculture/" target="_blank" rel="noopener">long used</a> by indigenous and pioneer farmers, these practices were historically limited by awareness, financial support, and insufficient investment in scientific research.</li>
<li>Voluntary climate finance via the voluntary carbon market (VCM) provided an initial spark&mdash;pulling together learnings from years of dispersed research, modeling, and local knowledge. Initial <a href="https://verra.org/methodologies/vm0042-improved-agricultural-land-management-v2-1/" target="_blank" rel="noopener">VCM</a> <a href="https://climateactionreserve.org/how/protocols/ncs/soil-enrichment/" target="_blank" rel="noopener">methodologies</a>, driven by private sector interest, brought academia and industry together to create guidance on quantifying, monitoring, and verifying carbon sequestration from regenerative practices. This spark generated new funding opportunities for farmers adopting climate-friendly practices worldwide and produced critical data to <a href="https://www.sciencedirect.com/science/article/pii/S0301479724022709" target="_blank" rel="noopener">advance understanding</a> and drive down <a href="https://www.edf.org/sites/default/files/documents/ag-soil-C-state-of-the-science.pdf" target="_blank" rel="noopener">scientific uncertainty</a> of the effectiveness of regenerative practices across diverse agricultural contexts.</li>
<li>Thanks in part to VCM-driven insights on where regenerative practices are most effective, they are increasingly prioritized within government and industry initiatives&mdash;practice-based incentives under <a href="https://www.nrcs.usda.gov/programs-initiatives/environmental-quality-incentives-program" target="_blank" rel="noopener">the</a> <a href="https://www.nrcs.usda.gov/programs-initiatives/csp-conservation-stewardship-program" target="_blank" rel="noopener">USDA</a>, adoption and uptake in France&rsquo;s <a href="https://www.i4ce.org/en/publication/six-years-carbon-certification-france-assessment-label-bas-carbone-climate/" target="_blank" rel="noopener">Label Bas-Carbone (Low Carbon Label) certification scheme</a>, as a critical component of the <a href="https://climate.ec.europa.eu/eu-action/carbon-removals-and-carbon-farming_en" target="_blank" rel="noopener">EU&rsquo;s Carbon Removal and Carbon Farming (EU CRCF)</a> framework, and via significant investments from agricultural giants including <a href="https://trellis.net/article/adm-regenerative-agriculture-5m-acres/" target="_blank" rel="noopener">ADM/PepsiCo</a>, <a href="https://www.cargill.com/sustainability/regenerative-agriculture" target="_blank" rel="noopener">Cargill</a>, and <a href="https://www.bayer.com/en/agriculture/regenerativeag" target="_blank" rel="noopener">Bayer</a>. Even while regenerative practices remain early in global uptake and we continue to need research to further reduce uncertainty, voluntary finance has provided policymakers and industry the testing ground to pilot incentives for broader adoption.</li>
</ul>
<h3>Enhanced Rock Weathering (ERW)</h3>
<ul>
<li>Close to home for Cascade is the surge of interest in <a href="https://cascadeclimate.org/Cascade%20Climate_Enhanced%20Rock%20Weathering%20101_vFinal.pdf" target="_blank" rel="noopener">enhanced rock weathering</a>&mdash;a durable carbon removal approach with agricultural benefits, including pH control and the potential for improved nutrient availability and higher yield impacts. Although similar in practice to traditional <a href="https://files.carbonplan.org/Aglime-Workshop-Report.pdf" target="_blank" rel="noopener">agricultural liming</a>, research on ERW as a climate and agronomic solution remained nascent until recently, with a small evidence base to draw from to understand its potential at scale and across diverse agricultural systems.&nbsp;</li>
<li>The initial interest in ERW via pilot projects supported by voluntary catalytic buyers brought the field together to define <a href="https://cascadeclimate.org/blog/foundations-for-carbon-removal-quantification-in-erw-deployments" target="_blank" rel="noopener">best practices</a> for carbon removal quantification, ensure that data from these commercial projects <a href="https://cascadeclimate.org/blog/data-sharing-system-for-erw" target="_blank" rel="noopener">could be shared</a> to advance learning and public trust, and <a href="https://cascadeclimate.org/blog/metal-accumulation-calculator" target="_blank" rel="noopener">define norms</a> for health and safety. While this remains a young field, learning is well underway, with leading buyers like <a href="https://frontierclimate.com/writing/lithos" target="_blank" rel="noopener">Frontier</a> and <a href="https://www.businesswire.com/news/home/20250403666345/en/Terradot-Signs-12000T-CDR-Deal-with-Microsoft-to-Advance-Critical-Scientific-Foundations-for-Enhanced-Rock-Weathering" target="_blank" rel="noopener">Microsoft</a> supporting high initial credit costs&mdash;currently on the order of <a href="https://cascadeclimate.org/Cascade%20Climate%20-%20Policy%20Priorities%20for%20Enhanced%20Rock%20Weathering.pdf" target="_blank" rel="noopener">$300 to $400 per ton</a> of carbon removal&mdash; and open data requirements. This allows for robust measurements to be conducted and science-advancing data that otherwise would remain proprietary to be collected and shared with researchers to advance the field long term.</li>
<li>These field-wide, learn-by-doing efforts have enabled critical insights around ERW&rsquo;s climate potential and <a href="https://cascadeclimate.org/blog/policy" target="_blank" rel="noopener">strengthened interest from policymakers</a> to consider ERW in emerging policy and compliance market frameworks&mdash;such as the <a href="https://cascadeclimate.org/blog/recommendations-from-foundations" target="_blank" rel="noopener">EU CRCF</a>&mdash;while increasing awareness of ERW&rsquo;s potential and buy-in from <a href="https://www.mpi.govt.nz/dmsdocument/62655-An-inventory-methodology-for-Enhanced-Rock-Weathering-ERW/" target="_blank" rel="noopener">governments</a> and <a href="https://agfundernews.com/eion-teams-up-with-perdue-for-enhanced-rock-weathering-in-landmark-carbon-insetting-deal" target="_blank" rel="noopener">industry</a> <a href="https://www.linkedin.com/pulse/nigerian-federal-government-partners-flux-advance-food-security-yu68f/" target="_blank" rel="noopener">across</a> <a href="https://www.mati.earth/mati-carbon-secures-innovative-debt-facility-to-scale-its-carbon-removal-business-globally-and-boost-climate-resilience/" target="_blank" rel="noopener">the</a> <a href="https://frontierclimate.com/writing/terradot" target="_blank" rel="noopener">globe</a>. This early bridge-building has the potential to open new revenue streams for farmers and increase access to pH management tools in nutrient-limited geographies down the road.</li>
</ul>
<p>We recognize that voluntary climate finance&mdash;especially for novel project types&mdash;has limits, including the risk of overstating early project benefits and complicating how those benefits are <a href="https://www.weforum.org/stories/2023/04/compensation-vs-contribution-comparing-climate-spending-models/" target="_blank" rel="noopener">&ldquo;claimed&rdquo;</a>. While <a href="https://sfi.stanford.edu/news/it-time-plan-c" target="_blank" rel="noopener">novel</a> <a href="https://newclimate.org/resources/publications/shifting-voluntary-climate-finance-to-the-high-hanging-fruit-of-climate" target="_blank" rel="noopener">approaches</a> to address these claims challenges have been proposed, practically speaking, voluntary climate finance has provided an imperfect-yet-effective tool to rapidly advance scientific learning, raise awareness, and build momentum&mdash;conditions that enable government and industry to engage via early innovation support.</p>
    
    </section>

    <section id="the-cost-gap">
        <h1>2. The Cost Gap</h1>
        <h2>Accelerating technologies down the cost curve—while discovering the true costs (and challenges) of climate opportunities.</h2>

        <p>Voluntary climate finance&mdash;both through the VCM and the early, voluntary stages of compliance programs&mdash;leverages markets to identify cost effective mitigation opportunities, helping to derisk technologies and demonstrate economic viability for regulation or industry uptake. In this sense, voluntary climate financing bridges the <span style="color: #0502b1;"><strong>cost gap</strong></span>, when price barriers prevent larger scale adoption.&nbsp;</p>
        <p>Ideally, the VCM accelerates the most cost-effective, high-mitigation-potential technologies. It helps move the approach towards cost parity for mainstream adoption and industry integration while demonstrating enough demand or scale potential to justify government support&mdash;as with renewable energy. Where technologies cannot compete on cost against incumbents, the VCM serves as a form of cost discovery, identifying the true costs of a given technology and barriers that cannot be overcome purely with market forces. This clarity allows policymakers to design fit-for-purpose price support programs that incentivize adoption.</p>
        <p>There are several prominent examples of the VCM closing the cost gap for promising technologies:&nbsp;</p>
        <h3>Renewable energy credits (RECs)</h3>
        <ul>
        <li>Early renewable energy technologies were prohibitively expensive compared to traditional energy technologies due to high capital costs, limited scale, and immature technology. <a href="https://www.energysage.com/other-clean-options/renewable-energy-credits-recs/" target="_blank" rel="noopener">Renewable energy credits (RECs)</a> provided a vehicle to use market-based programs to absorb price premiums during initial technology phases. Voluntary demand for renewable energy and <a href="https://www.iea.org/reports/renewable-energy-market-update-june-2023/are-market-forces-overtaking-policy-measures-as-the-driving-force-behind-wind-and-solar-pv" target="_blank" rel="noopener">private sector interest</a> in RECs contributed meaningfully to cost declines by sending a powerful signal of future demand, which drove manufacturing to scale. Early leaders like <a href="https://clean-coalition.org/feed-in-tariffs/lessons-from-germany/" target="_blank" rel="noopener">Germany</a> and <a href="https://www.pivotenergy.net/blog/new-jerseys-new-solar-incentive-framework" target="_blank" rel="noopener">New Jersey</a> created generous price incentives for solar that were intended to jump-start a new market, rather than being designed purely on economic grounds. Catalytic, energy-consuming corporate buyers created early offtake demand and drove innovation in procurement, aggregation, and financing&mdash;including corporate renewable power purchase agreements&mdash;while signaling the <a href="https://www.novoco.com/periodicals/articles/corporate-ppas-drive-us-clean-energy-growth-how-voluntary-offtake-agreements-mitigate-risks-and-enable-financing" target="_blank" rel="noopener">long term demand</a> necessary for renewable supply chain investment. In the crucial early period of renewables development, voluntary financing played a supporting role in market formation and discovering curve cost reductions.&nbsp;</li>
        <li>As renewables became increasingly cost competitive in the 2010s&mdash;partly due to early market development work&mdash;policymakers were able to confidently set higher ambition renewable portfolio standards without fear that the policy would be too costly for industry. This led to the natural <a href="https://www.msci.com/research-and-insights/blog-post/renewable-energy-carbon-credits-losing-steam" target="_blank" rel="noopener">phasing out of RECs</a> in the VCM as renewable penetration rates increased and additionality in mature markets declined&mdash;and eventually, to the <a href="https://www.iea.org/data-and-statistics/charts/share-of-renewable-electricity-generation-by-technology-2000-2030" target="_blank" rel="noopener">widespread adoption</a> of renewables we see globally today.&nbsp;</li>
        </ul>
        <p>Voluntary climate financing can also &ldquo;nudge&rdquo; industry or policy to act on low-cost mitigation opportunities that are otherwise overlooked:</p>
        <h3>Landfill gas capture and utilization projects&nbsp;</h3>
        <ul>
        <li><a href="https://icvcm.org/landfill-gas-capture/" target="_blank" rel="noopener">Landfill projects</a> involve the voluntary installation of gas collection and control systems (GCCS) and methane destruction devices on landfill sites beyond regulatory requirements. While these projects are now seen as <a href="https://19january2017snapshot.epa.gov/global-mitigation-non-co2-greenhouse-gases/global-mitigation-non-co2-greenhouse-gases-landfills_.html" target="_blank" rel="noopener">cost effective</a>, relatively mature, and <a href="https://www.msci.com/research-and-insights/blog-post/the-first-core-carbon-principles-qualifying-projects-the-vcm-steps-on-the-gas" target="_blank" rel="noopener">consistently high quality</a>, landfill owners had fewer incentives to invest in these projects without the &ldquo;pull&rdquo; of voluntary financing.</li>
        <li>Early VCM projects demonstrated that installations of landfill methane collection systems can often be done at a low dollar per CO<sub>2</sub>e cost.<em> </em>These projects also produced valuable data that helped to establish cost benchmarks internationally and informed government policies and support mechanisms. Over time, these <a href="https://www.epa.gov/lmop/resources-funding-landfill-gas-energy-projects" target="_blank" rel="noopener">government programs</a>&mdash;such as tax credits and exemptions, production incentives, loans, and grants&mdash;combined with revenue opportunities from renewable natural gas made gas-capture systems <a href="https://www.epa.gov/lmop" target="_blank" rel="noopener">standard practice</a> in many regions, particularly in developed markets like the US. This creates the optimal outcome: with the right safeguards in place, high-quality VCM projects <a href="https://bezerocarbon.com/insights/assessing-the-quality-of-landfill-gas-projects" target="_blank" rel="noopener"><em>lose additionality over time</em></a> as costs are internalized and regulation takes over in mature markets, while still providing a needed voluntary push in less developing markets.</li>
        </ul>

        <img
		src={landfill}
		alt="Chart that depicts the total number of landfill gas projects in the U.S. against the number participating in the VCM, illustrating the “push” from VCM activity and flattening enrollment as additionality is reduced - via BeZeroand the EPA. "
	/>
    
        <p style="text-align: center;">
            <em>
                Total number of landfill gas projects in the U.S. against the number participating in the VCM, illustrating the &ldquo;push&rdquo; from VCM activity and flattening enrollment as additionality is reduced - 
            </em>
            <a href="https://bezerocarbon.com/insights/assessing-the-quality-of-landfill-gas-projects" target="_blank" rel="noopener">
                <em>via BeZero</em>
            </a>
            <em> and the EPA.&nbsp;</em>
        </p>

    </section>  

    <section id="the-deployment-readiness-gap">
        <h1>3. The Deployment Readiness Gap</h1>
        <h2>Providing the testing ground to address barriers to scale up and reduce project execution risks.&nbsp;</h2>

        <p>Even &ldquo;known&rdquo; solutions that seem like no-brainers to deploy at scale face real-world adoption barriers beyond scientific and cost challenges, including assessing system-level impacts beyond project boundaries, managing environmental risks at scale, and supporting community adoption and buy-in. This gap differs from the knowledge gap in that even when the scientific basis is sound&mdash;and pre-market or limited-scale efforts are conducted to identify and address foreseeable risks&mdash;project implementation surfaces challenges that were not anticipated in the design stage. Voluntary efforts provide a lower-risk testing ground to refine deployment approaches and build best practices for scale-up and policy uptake&mdash;with voluntary climate financing bridging this <span style="color: #ff7f0e;"><strong>deployment readiness gap</strong></span>. There are several prominent examples of this:&nbsp;</p>
<h3>Avoided deforestation</h3>
<ul>
<li>Deforestation exemplifies a classic market failure: landowners profit from timber sales and face economic pressure to convert land for agricultural use, but have limited incentives to protect the services that intact forests provide&mdash;including carbon storage, biodiversity conservation, and watershed protection. Alongside policy efforts, voluntary climate finance provides one vehicle to keep standing forests intact where other conservation approaches are limited. However, early initiatives to finance avoided deforestation faced <a href="https://www.cifor-icraf.org/publications/pdf_files/Books/BAngelsen1801.pdf" target="_blank" rel="noopener">deployment challenges</a> around accurate quantification of carbon benefits and unanticipated social impacts related to land tenure insecurity, conflicts over forest ownership, and unclear benefit distribution for local communities, leading to <a href="https://www.theguardian.com/environment/2023/jan/18/revealed-forest-carbon-offsets-biggest-provider-worthless-verra-aoe" target="_blank" rel="noopener">intense public scrutiny</a> of projects.</li>
<li>The UNFCCC created the <a href="https://unfccc.int/topics/land-use/workstreams/redd/what-is-redd" target="_blank" rel="noopener">REDD+ framework</a> as a policy tool to quantify the climate benefits of&mdash;and facilitate developed country capital into&mdash;projects that reduce deforestation at the jurisdictional level. Voluntary interest in forest protection quickly followed, pushing private capital to explore <a href="https://www.forestcarbonpartnership.org/what-jurisdictional-scale-redd" target="_blank" rel="noopener">project-based</a> <a href="https://calyxglobal.com/research-hub/research/an-introduction-to-jurisdictional-REDD/" target="_blank" rel="noopener">avoided deforestation</a> efforts. Early implementation challenges at the project level forced iterative improvements via high visibility <a href="https://gspp.berkeley.edu/assets/uploads/page/Quality-Assessment-of-VM0048--July-2024--BCTP-Policy-Brief.pdf" target="_blank" rel="noopener">methodological updates</a> to improve quantification and social safeguards, as well as new requirements to integrate <a href="https://verra.org/worlds-largest-carbon-program-pilots-digital-measuring-of-forest-carbon/" target="_blank" rel="noopener">remote sensing-based monitoring</a>. Over time, experience with project-level REDD and continued policy progress enabled the voluntary market to evolve towards <a href="https://calyxglobal.com/research-hub/research/an-introduction-to-jurisdictional-REDD/" target="_blank" rel="noopener">&ldquo;nested&rdquo;</a> jurisdictional approaches, where forest countries could integrate individual projects into national schemes and <a href="https://www.forestcarbonpartnership.org/what-jurisdictional-scale-redd" target="_blank" rel="noopener">more holistically address</a> the deployment risks of individual projects at subnational and national scales.&nbsp;</li>
<li>The <a href="https://www.leafcoalition.org/home" target="_blank" rel="noopener">LEAF Coalition</a>&mdash;a jurisdictional-based public-private partnership focused on halting tropical deforestation&mdash;is a recent example of an approach to build out the &ldquo;middle&rdquo; of the bridge on the back of VCM activities:&nbsp;</li>
<ul>
<li>Enabling countries and provinces to <a href="https://emergentclimate.com/wp-content/uploads/2024/09/Para-ERPA-announcement-Emergent-Final.pdf" target="_blank" rel="noopener">participate directly</a> on the supply side, backed by guaranteed <a href="https://www.leafcoalition.org/corporations" target="_blank" rel="noopener">private sector VCM demand</a>.&nbsp;</li>
<li>Setting strict <a href="https://resources.leafcoalition.org/wp-content/uploads/2023/08/Emergent-Forest-Government-Eligibility-criteria.pdf" target="_blank" rel="noopener">eligibility criteria</a> for forest governments, including emissions targets, the inclusion of forests in participating countries Nationally Determined Contributions (NDCs), and robust forest monitoring in line with updated <a href="https://www.artredd.org/trees/" target="_blank" rel="noopener">carbon accounting best practices</a>.</li>
<li>Pooling commitments and sharing risk&mdash;such as <a href="https://www.leafcoalition.org/donor-governments" target="_blank" rel="noopener">country-backed</a> purchase guarantees&mdash;to strengthen public-private ties and prevent any single actor from bearing all financial or reputational risk.</li>
</ul>
<li>While work remains to advance solutions for deforestation&mdash;both within and beyond the market context&mdash;voluntary action has provided a way for private capital to support and accelerate ongoing bilateral and multilateral efforts. Early voluntary market support and initiatives like LEAF, the World Bank&rsquo;s <a href="https://www.forestcarbonpartnership.org/" target="_blank" rel="noopener">Forest Carbon Partnership Facility</a>, and others have directly influenced <a href="https://news.mongabay.com/2025/03/what-have-we-learned-from-15-years-of-redd-policy-research-analysis" target="_blank" rel="noopener">policy reforms</a> in forest nations, laid the groundwork for broader policy uptake, and positioned REDD+ for its <a href="https://www.nature.org/content/dam/tnc/nature/en/documents/COP29-Article-6-Key-Outcomes.pdf" target="_blank" rel="noopener">current</a> inclusion under Article 6.2 and likely <a href="https://www.woodwellclimate.org/article-6-4-natural-climate-solutions/" target="_blank" rel="noopener">future</a> inclusion under the Article 6.4 Paris Agreement Crediting Mechanism.&nbsp;</li>
</ul>

<img
src={redd}
alt="The history of REDD+ in form of a pictoral timeline - via VCMprimer from Climate Focus."
/>

<p style="text-align: center;">
    <em>The history of REDD+ - via </em>
    <a href="https://vcmprimer.org/chapter-14-how-can-the-voluntary-carbon-market-support-redd/" target="_blank" rel="noopener">
        <em>VCMprimer </em>
    </a>
    <em> from Climate Focus</em>.
</p>

<h3>Clean cookstove projects</h3>
<ul>
<li>Clean cookstove projects use carbon finance to replace polluting fuels with efficient stoves&mdash;cutting emissions, easing pressure on forests, and providing public health benefits. However, like avoided deforestation, executing these projects has proven difficult in practice. The approach has faced a number of <a href="https://calyxglobal.com/research-hub/research/cooking-up-quality-carbon-credits-from-efficient-cookstove-projects-face-integrity-issues-worth-fixing/#:~:text=Besides%20overestimation%2C%20there%20is%20also,this%20risk%20for%20cookstove%20projects." target="_blank" rel="noopener">implementation issues</a> related to project integrity, including overestimations of emissions reductions, risks that nearby forests could still be cut or burned, and insufficient support for community adoption.&nbsp;</li>
<li>Trial-and-error via the VCM&mdash;in particular, significant <a href="https://bezerocarbon.com/insights/cooking-with-quality-improving-cookstoves" target="_blank" rel="noopener">methodological and data collection improvements</a> over the past decade-plus&mdash;enabled on-the-ground learning that improved measurement accuracy and social safeguards, ensuring that benefits were not overestimated and that project benefits flowed more directly into the communities implementing the changes. This included enhanced monitoring of stove usage through in-person follow-up surveys and Stove-Use Monitors which improved data accuracy and project reporting, boosting transparency and confidence in project impacts.&nbsp;</li>
<li>As the climate integrity of projects improved and implementation matured, best practice frameworks&mdash;such as the Clean Cooking Alliance&rsquo;s recently developed <a href="https://cleancooking.org/news/cca-launches-principles-for-responsible-carbon-finance-in-clean-cooking/" target="_blank" rel="noopener">Principles for Responsible Carbon Finance in Clean Cooking</a> and <a href="https://cleancooking.org/wp-content/uploads/2025/02/Buyers-Guide-to-Cookstove-Credits.pdf" target="_blank" rel="noopener">Buyer&rsquo;s Guide</a>&mdash;crowded in both public and private sector organizational commitments and support for the approach. This continued iteration has contributed to the inclusion of household energy or clean cooking goals in <a href="https://blogs.worldbank.org/en/energy/balancing-opportunity-and-risk-harnessing-carbon-markets-expand-clean-cooking" target="_blank" rel="noopener">country NDCs</a> and mobilized support via government-run and multi-lateral -financed <a href="https://www.esmap.org/clean-cooking-fund" target="_blank" rel="noopener">programs</a>&mdash;such as the <a href="https://www.worldbank.org/en/news/press-release/2020/09/17/world-bank-project-to-boost-household-access-to-affordable-energy" target="_blank" rel="noopener">Rwanda Energy Access and Quality Improvement Project</a>&mdash;as funders could more readily rely on the measurable impact of projects to justify their investments.</li>
</ul>
<p>These examples have gotten us closer to the end of the bridge in some jurisdictions, while there is still work to be done in others. For both approaches, years of testing and iterative improvement in the VCM clarified what was needed to ensure their effectiveness and produced de-risked tools, including best practices for carbon quantification, project implementation, and community engagement. In turn, these tools could provide a starting point for governments and financiers to take implementation to the next stage.</p>
        
    </section>

    <section id="looking-forward">
        <h1>Looking Forward</h1>

        <p>While no mitigation technology will follow the exact same path to a sustainable end state, the types of gaps they face and the need to engage &ldquo;far side&rdquo; actors early remain constant. In an era of deregulation and waning climate ambition, voluntary market mechanisms are more critical than ever&mdash;among the few tools left to demonstrate real impact and position mitigation approaches for integration once policy ambition returns.</p>

        <p>Today, super pollutant mitigation approaches vary widely in their maturity and how far along they are in closing knowledge, cost, and deployment readiness gaps. Progress has already been made to advance these solutions, even without the spotlight.&nbsp;</p>
        <p>Some project types within super pollutants&mdash;like landfill methane gas capture&mdash;are far along on their journey across the bridge already, and targeted attention, momentum, and capital can help get them all the way across. Other, earlier-stage super pollutant project types&mdash;like HFC destruction&mdash;are just beginning to see their first wave of projects, and voluntary climate finance will be a critical tool to demonstrate impact through iterative learning, kickstarting the journey towards policy and industry value chain integration.</p>
        <p>Stay tuned for more detail on how we plan to put these perspectives into action.</p>

    </section>

    
</main>
<img style="width: 0%;" src={grants} alt="Enhanced Rock Weathering" />
</div>

