/** Generated from V5.0 LRM Cost Model.xlsx · V4.5 SEA Data */
export default {
  "version": "5.0",
  "geography": "Southeast Asia",
  "rows": [
    {
      "stage": "Recovery",
      "geography": "Southeast Asia",
      "variable": "Central Facility Operational Activities \n\nConsolidation into Large Volume Cylinders and/or ton tanks",
      "scenario": "Low",
      "cost": 0.5,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 3
    },
    {
      "stage": "Recovery",
      "geography": "Southeast Asia",
      "variable": "Central Facility Operational Activities \n\nConsolidation into Large Volume Cylinders and/or ton tanks",
      "scenario": "Medium",
      "cost": 0.75,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 4
    },
    {
      "stage": "Recovery",
      "geography": "Southeast Asia",
      "variable": "Central Facility Operational Activities \n\nConsolidation into Large Volume Cylinders and/or ton tanks",
      "scenario": "High",
      "cost": 1.0,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 5
    },
    {
      "stage": "Recovery",
      "geography": "Southeast Asia",
      "variable": "Recovery machine (basic, portable)",
      "scenario": null,
      "cost": 1000.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 6
    },
    {
      "stage": "Recovery",
      "geography": "Southeast Asia",
      "variable": "Recovery accessories (basic, per set)",
      "scenario": null,
      "cost": 1500.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 7
    },
    {
      "stage": "Recovery",
      "geography": "Southeast Asia",
      "variable": "Recovery accessories (for AC pump down, per set)",
      "scenario": null,
      "cost": 500.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 8
    },
    {
      "stage": "Recovery",
      "geography": "Southeast Asia",
      "variable": "Recovery machine (high capacity)",
      "scenario": null,
      "cost": 20000.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 9
    },
    {
      "stage": "Recovery",
      "geography": "Southeast Asia",
      "variable": "Recovery accessories (high capacity, per set)",
      "scenario": null,
      "cost": 4500.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 10
    },
    {
      "stage": "Recovery",
      "geography": "Southeast Asia",
      "variable": "Refrigerant Identifiers",
      "scenario": null,
      "cost": 10000.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 11
    },
    {
      "stage": "Recovery",
      "geography": "Southeast Asia",
      "variable": "Recovery Cylinders (small ~10kg capacity)",
      "scenario": null,
      "cost": 250.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 12
    },
    {
      "stage": "Recovery",
      "geography": "Southeast Asia",
      "variable": "Recovery Cylinders (large ~50kg capacity)",
      "scenario": null,
      "cost": 350.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 13
    },
    {
      "stage": "Recovery",
      "geography": "Southeast Asia",
      "variable": "Ton Tanks",
      "scenario": null,
      "cost": 5000.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 14
    },
    {
      "stage": "Recovery",
      "geography": "Southeast Asia",
      "variable": "Tracking & Monitoring System",
      "scenario": null,
      "cost": 50000.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 15
    },
    {
      "stage": "Transport & Handling to End-Use Facility (for reclamation / destruction)",
      "geography": "Southeast Asia",
      "variable": "In-country",
      "scenario": "Low",
      "cost": 0.2,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 17
    },
    {
      "stage": "Transport & Handling to End-Use Facility (for reclamation / destruction)",
      "geography": "Southeast Asia",
      "variable": "In-country",
      "scenario": "Medium",
      "cost": 0.4,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 18
    },
    {
      "stage": "Transport & Handling to End-Use Facility (for reclamation / destruction)",
      "geography": "Southeast Asia",
      "variable": "In-country",
      "scenario": "High",
      "cost": 0.6,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 19
    },
    {
      "stage": "Transport & Handling to End-Use Facility (for reclamation / destruction)",
      "geography": "Southeast Asia",
      "variable": "Exported",
      "scenario": "Low",
      "cost": 4.0,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 20
    },
    {
      "stage": "Transport & Handling to End-Use Facility (for reclamation / destruction)",
      "geography": "Southeast Asia",
      "variable": "Exported",
      "scenario": "Medium",
      "cost": 5.0,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 21
    },
    {
      "stage": "Transport & Handling to End-Use Facility (for reclamation / destruction)",
      "geography": "Southeast Asia",
      "variable": "Exported",
      "scenario": "High",
      "cost": 6.0,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 22
    },
    {
      "stage": "Destruction",
      "geography": "Southeast Asia",
      "variable": "Plasma Arc",
      "scenario": "Low",
      "cost": 5.0,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 24
    },
    {
      "stage": "Destruction",
      "geography": "Southeast Asia",
      "variable": "Plasma Arc",
      "scenario": "Medium",
      "cost": 6.5,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 25
    },
    {
      "stage": "Destruction",
      "geography": "Southeast Asia",
      "variable": "Plasma Arc",
      "scenario": "High",
      "cost": 8.0,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 26
    },
    {
      "stage": "Destruction",
      "geography": "Southeast Asia",
      "variable": "Rotary Kiln Incineration",
      "scenario": "Low",
      "cost": 6.0,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 27
    },
    {
      "stage": "Destruction",
      "geography": "Southeast Asia",
      "variable": "Rotary Kiln Incineration",
      "scenario": "Medium",
      "cost": 7.0,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 28
    },
    {
      "stage": "Destruction",
      "geography": "Southeast Asia",
      "variable": "Rotary Kiln Incineration",
      "scenario": "High",
      "cost": 8.0,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 29
    },
    {
      "stage": "Destruction",
      "geography": "Southeast Asia",
      "variable": "Cement Kiln Incineration",
      "scenario": "Low",
      "cost": 6.0,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 30
    },
    {
      "stage": "Destruction",
      "geography": "Southeast Asia",
      "variable": "Cement Kiln Incineration",
      "scenario": "Medium",
      "cost": 7.0,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 31
    },
    {
      "stage": "Destruction",
      "geography": "Southeast Asia",
      "variable": "Cement Kiln Incineration",
      "scenario": "High",
      "cost": 8.0,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 32
    },
    {
      "stage": "Destruction",
      "geography": "Southeast Asia",
      "variable": "Rotary Kiln (Existing)",
      "scenario": null,
      "cost": 0.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 33
    },
    {
      "stage": "Destruction",
      "geography": "Southeast Asia",
      "variable": "Rotary Kiln (Retrofit)",
      "scenario": null,
      "cost": 200000.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 34
    },
    {
      "stage": "Destruction",
      "geography": "Southeast Asia",
      "variable": "Rotary Kiln (New Facility)",
      "scenario": null,
      "cost": 3500000.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 35
    },
    {
      "stage": "Destruction",
      "geography": "Southeast Asia",
      "variable": "Cement Kiln (Existing)",
      "scenario": null,
      "cost": 0.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 36
    },
    {
      "stage": "Destruction",
      "geography": "Southeast Asia",
      "variable": "Cement Kiln (Retrofit)",
      "scenario": null,
      "cost": 200000.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 37
    },
    {
      "stage": "Destruction",
      "geography": "Southeast Asia",
      "variable": "Cement Kiln (New Facility)",
      "scenario": null,
      "cost": 3500000.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 38
    },
    {
      "stage": "Destruction",
      "geography": "Southeast Asia",
      "variable": "Plasma Arc (Existing)",
      "scenario": null,
      "cost": 0.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 39
    },
    {
      "stage": "Destruction",
      "geography": "Southeast Asia",
      "variable": "Plasma Arc (New Facility)",
      "scenario": null,
      "cost": 5000000.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 40
    },
    {
      "stage": "Destruction",
      "geography": "Southeast Asia",
      "variable": "Admin & Licensing",
      "scenario": null,
      "cost": 10000.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 41
    },
    {
      "stage": "Reclamation",
      "geography": "Southeast Asia",
      "variable": "Reclamation Cost",
      "scenario": "Low",
      "cost": 5.5,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 43
    },
    {
      "stage": "Reclamation",
      "geography": "Southeast Asia",
      "variable": "Reclamation Cost",
      "scenario": "Medium",
      "cost": 8.5,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 44
    },
    {
      "stage": "Reclamation",
      "geography": "Southeast Asia",
      "variable": "Reclamation Cost",
      "scenario": "High",
      "cost": 11.5,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 45
    },
    {
      "stage": "Reclamation",
      "geography": "Southeast Asia",
      "variable": "Reclamation Training",
      "scenario": null,
      "cost": 625.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 46
    },
    {
      "stage": "Reclamation",
      "geography": "Southeast Asia",
      "variable": "Reclamation Facility (Existing)",
      "scenario": null,
      "cost": 0.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 47
    },
    {
      "stage": "Reclamation",
      "geography": "Southeast Asia",
      "variable": "Reclamation Facility (New Facility, Basic)",
      "scenario": null,
      "cost": 850000.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 48
    },
    {
      "stage": "Reclamation",
      "geography": "Southeast Asia",
      "variable": "Reclamation Facility (Retrofit)",
      "scenario": null,
      "cost": null,
      "costLabel": "NA – Existing or New Facility only",
      "capexOpex": "Capex",
      "systemType": null,
      "row": 49
    },
    {
      "stage": "Reclamation",
      "geography": "Southeast Asia",
      "variable": "Gas Chromatography (Full lab)",
      "scenario": null,
      "cost": 225000.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 50
    },
    {
      "stage": "Reclamation",
      "geography": "Southeast Asia",
      "variable": "Admin & Licensing",
      "scenario": null,
      "cost": 10000.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 51
    },
    {
      "stage": "Recycling",
      "geography": "Southeast Asia",
      "variable": "Recycling Costs (% mark up from normal recovery cost)",
      "scenario": null,
      "cost": 0.5,
      "costLabel": null,
      "capexOpex": "Opex",
      "systemType": null,
      "row": 53
    },
    {
      "stage": "Recycling",
      "geography": "Southeast Asia",
      "variable": "Recycling Equipment (Basic)",
      "scenario": null,
      "cost": 1800.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 54
    },
    {
      "stage": "Recycling",
      "geography": "Southeast Asia",
      "variable": "Recycling Equipment (High capacity)",
      "scenario": null,
      "cost": 20000.0,
      "costLabel": null,
      "capexOpex": "Capex",
      "systemType": null,
      "row": 55
    }
  ]
};
